# Generated by Django 5.2.4 on 2025-07-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(choices=[('sprint semanal', 'sprint_semanal'), ('sprint mensal', 'sprint_mensal'), ('sprint anual', 'sprint_anual')], default='sprint semanal', max_length=14),
        ),
    ]
