# Generated by Django 5.2.4 on 2025-07-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefas_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='data_finalizacao',
            field=models.DateField(auto_now=True),
        ),
    ]
