# Generated by Django 5.2.4 on 2025-07-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_remove_tarefas_data_finalizacao_tarefas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(choices=[('sprint semanal', 'sprint semanal'), ('sprint quinzenal', 'sprint quinzenal'), ('sprint mensal', 'sprint mensal'), ('sprint anual', 'sprint anual')], default='sprint semanal', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Em procrastinação', 'Em procrastinação'), ('Finalizado', 'Finalizado'), ('Em aberto', 'Em aberto')], default='Em aberto', max_length=18),
        ),
    ]
