# Generated by Django 5.2.4 on 2025-07-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefas_categoria_alter_tarefas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em andamento', 'Em andamento'), ('Em procrastinação', 'Em procrastinação'), ('Finalizado', 'Finalizado')], default='Em aberto', max_length=18),
        ),
    ]
