# Generated by Django 5.2.4 on 2025-07-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
