# Generated by Django 5.2.4 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_tarefas_descricao_alter_tarefas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Andamento', 'Andamento'), ('Stand-by', 'Stand-by'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=18),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
