# Generated by Django 5.2.4 on 2025-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefas_status_alter_tarefas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('aberto', 'aberto'), ('andamento', 'andamento'), ('standby', 'standby'), ('finalizado', 'finalizado')], default='aberto', max_length=18),
        ),
    ]
