# Generated by Django 5.2.4 on 2025-07-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_code',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
