# Generated by Django 5.2.4 on 2025-07-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_team_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_code',
        ),
    ]
